version: '3'
services:
  database:
    image: mysql:latest
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - database
    image: wordpress:latest
    volumes:
      - ./wp:/var/www/html
      - ./plugins:/var/www/html/wp-content/plugins
      - ./theme:/var/www/html/wp-content/themes
    ports:
      - "4040:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    links:
      - database:db
    ports:
      - "4000:80"
